export const SCOPE_CONFIG = {
  ACTION: {
    READ: 'READ',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    IMPORT_FROM_CSV: 'IMPORT_FROM_CSV',
    LINK_KIT: 'LINK_KIT',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    CHANGE_STATUS_MANUALLY: 'CHANGE_STATUS_MANUALLY',
    RESTORE: 'RESTORE',
    PRINT_LABEL: 'PRINT_LABEL',
    EXPORT: 'EXPORT',
    TRANSFER: 'TRANSFER',
  },
  ENTITY: {
    USERS: 'users',
    TENANTS: 'tenants',
    PRODUCTS: 'products',
    PROJECTS: 'projects',
    SURVEYS: 'survey',
    TENANT_PARENT: 'tenant-parent',
    PROFILES: 'profiles',
    BATCHES: 'batches',
    KITS: 'kits',
    SAMPLES: 'samples',
    SEQUENCES: 'sequences',
    USER_ADDRESS: 'user-address',
    TENANT_ADDRESS: 'tenant-address',
    FOODS: 'foods',
    COACH_PROFILE: 'coach-profile',
    ORDER: 'orders',
    COACH_PROGRAM: 'coach-program',
    COACH_BOOKING: 'coach-booking',
    HOME_PAGE_RULE: 'home-page-rule',
    ADMIN_SETTINGS: 'admin-setting',
    REPORTS: 'kit-report',
    EMAILS: 'emails',
  },
};
